# Generated by Django 5.2.3 on 2025-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
