# Generated by Django 5.2.3 on 2025-07-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_empleado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
