# Generated by Django 5.2.3 on 2025-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_empleado_segundo_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
