# Generated by Django 5.2.3 on 2025-07-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='Departamento',
            new_name='departamento',
        ),
    ]
