# Generated by Django 5.2.3 on 2025-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0002_rename_departamento_reunion_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='documento',
            field=models.BigIntegerField(),
        ),
    ]
